language: cpp
dist: trusty

env:
  global:
    secure: BNHKvLV0AYlKlVq9upiip72P0lHK0P7XbhxIMAqM3KEwpedwW2DQw6BF+y5J2RTrMhhvFzKchNwO5hrY0Wpg0wn0/JHgVBTw5pobRs7CBuRzf5vCK/V8ulJO4hwf/6ly92gobHEduCWhhsFZ7q1Jf1a0nIzl3v9j+KwzDCKB/+vAahKw9A3ggDrhe3FYxHrPdqtqOzKjy8HLMX4hFwf2+6BoIRuiaobEAVousBnrV4XNpaTVuLKzOD9ZAvlcuW6Ivhj91IvwCqr+4Hq6mieK76Ozte/2BVcXjsvqglGyIqDBZvemNGFGMJWA5Fazcdy3BbbTdbpejXPCIL5csV+NBAiPEOZe/pz0asrPHN6JJn/19Q/ebSpZR7Xb/ii3vy9jqrmMYK2J8KK888meMZbaxJV27zcIfO7h9XkPNAXD1GTjik0wLrGxb9HKkn49dR8oXXZfz5JgWiygp9IAYQBhE0WgyjAFMKN0Bi07OuDTZEtRElwZpXvBR1Tdepa1DIf38fBlQ+jLk+fg4l4I96dS8kNXQXEtRob860EYyEiFc7MYtVQEoVerCeOrdhhpJfzPg5S13EmoZjhYa4SkDJumGNGOOXmMylS2xfEHV9BK5CbwROwuf0dtXkF60k/hUaBZFRa6rUJ6g70N5osVtfWXovYr4g+Z8pa6g+czCObqVRc=

addons:
    apt:
        sources:
          # add PPAs with more up-to-date toolchains
          - ubuntu-toolchain-r-test
        packages:
          # install toolchains
          - g++-5


matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

    - os: osx
      language: generic
      osx_image: xcode8
      env:
        - MB_PYTHON_VERSION=2.7

script:
  - mkdir build
  - cd build
  - cmake  -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=../install ..
  - make
  - cd ../
  - python setup.py sdist bdist_wheel

deploy:
        provider: test.pypi
        user: "thompson318"
        password:
                secure: BNHKvLV0AYlKlVq9upiip72P0lHK0P7XbhxIMAqM3KEwpedwW2DQw6BF+y5J2RTrMhhvFzKchNwO5hrY0Wpg0wn0/JHgVBTw5pobRs7CBuRzf5vCK/V8ulJO4hwf/6ly92gobHEduCWhhsFZ7q1Jf1a0nIzl3v9j+KwzDCKB/+vAahKw9A3ggDrhe3FYxHrPdqtqOzKjy8HLMX4hFwf2+6BoIRuiaobEAVousBnrV4XNpaTVuLKzOD9ZAvlcuW6Ivhj91IvwCqr+4Hq6mieK76Ozte/2BVcXjsvqglGyIqDBZvemNGFGMJWA5Fazcdy3BbbTdbpejXPCIL5csV+NBAiPEOZe/pz0asrPHN6JJn/19Q/ebSpZR7Xb/ii3vy9jqrmMYK2J8KK888meMZbaxJV27zcIfO7h9XkPNAXD1GTjik0wLrGxb9HKkn49dR8oXXZfz5JgWiygp9IAYQBhE0WgyjAFMKN0Bi07OuDTZEtRElwZpXvBR1Tdepa1DIf38fBlQ+jLk+fg4l4I96dS8kNXQXEtRob860EYyEiFc7MYtVQEoVerCeOrdhhpJfzPg5S13EmoZjhYa4SkDJumGNGOOXmMylS2xfEHV9BK5CbwROwuf0dtXkF60k/hUaBZFRa6rUJ6g70N5osVtfWXovYr4g+Z8pa6g+czCObqVRc=
        on:
                tags: true
