language: cpp
sudo: required
dist: trusty

env:
  global:

matrix:
  include:

    - os: osx
      osx_image: xcode8
      env:
        - PYTHON_VERSION=2.7
    
    - os: osx
      osx_image: xcode8
      env:
        - PYTHON_VERSION=3.6


script:
  - mkdir build
  - cd build
  - cmake  -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF ..
  - make
  - cd ../

