language: cpp
sudo: required
dist: trusty
addons:
    apt:
        sources:
          # add PPAs with more up-to-date toolchains
          - ubuntu-toolchain-r-test
        packages:
          # install toolchains
          - g++-5

    artifacts: true
        paths:
          - dist/

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

before_install:
  - |
    wget -q https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh
    sh cmake-3.6.3-Linux-x86_64.sh --skip-license

script:
  - mkdir build
  - mkdir install
  - cd build
  - ../bin/cmake  -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=../install ..
  - make
  - cd ../
  - python setup.py sdist bdist_wheel

