version: "{build}"

os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\ndicapi

shallow_clone: false

skip_commits:
  message: /\[av skip\]/

environment:
  matrix:
          #- COMPILER: "Visual Studio 14 Win64"
          # PYTHON: "C:\\Python27-x64"
    - COMPILER: "Visual Studio 14 Win64"
      PYTHON: "C:\\Python36-x64"

    - COMPILER: "Visual Studio 14 Win64"
      PYTHON: "C:\\Python27-x64"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"

platform:
  - x64

configuration:
  - Release

matrix:
  fast_finish: true


before_build:
  - echo --------------------------------------------------------------------------------
  - echo Appveyor environment info:
  - echo COMPILER = %COMPILER%, CONFIGURATION = %CONFIGURATION%
  - cmake -version
  - pwd
  - git submodule update -q --init --recursive
  - set PATH=C:\Python36-x64;%PATH%
  - rem --------------------------------------------------------------------------------

build_script:
  - echo --------------------------------------------------------------------------------
  - echo Build ndicapi:
  - mkdir build
  - mkdir install
  - cd build
  - cmake -G "%COMPILER%" -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=../install --config %CONFIGURATION% ..
  - cmake --build . --config %CONFIGURATION%
  - cd ../

