on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        python-ver: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, windows-latest, macos-latest]
        experimental: [false]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-ver }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine auditwheel
      
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.0.2

      - name: build Windows
        if: matrix.os == 'windows-latest'
        run: |
          mkdir build
          mkdir install
          cd build
          cmake -G "Visual Studio 14 Win64" -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=../install ..
          cmake --build . 
          cd ../
          python.exe setup.py sdist bdist_wheel --plat-name win_amd64
          python -m twine upload -u __token__ -p ${{secrets.PYPI_API_TOKEN}} dist/* --skip-existing

      - name: build ubuntu 
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir build
          cd build
          cmake  -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF ..
          make
          cd ..
          python setup.py sdist bdist_wheel 
          python -m auditwheel repair dist/ndicapi*linux_x86_64.whl
          python -m twine upload -u __token__ -p ${{secrets.PYPI_API_TOKEN}} dist/*manylinux* --skip-existing

      - name: build macos
        if: matrix.os == 'macos-latest'
        run: |
          mkdir build
          cd build
          cmake  -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF ..
          make
          cd ..
          python setup.py sdist bdist_wheel
          python -m twine upload -u __token__ -p ${{secrets.PYPI_API_TOKEN}} dist/* --skip-existing

