on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        python-ver: [3.7, 3.8, 3.9]
        os: [windows-latest]
        experimental: [false]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-ver }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine auditwheel
      
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16]'

      - name: build Windows
        if: matrix.os == 'windows-latest'
        run: |
          mkdir build
          mkdir install
          cd build
          cmake -G "Visual Studio 16" -A Win64 -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=../install ..
          cmake --build . 
          cd ../
          python.exe setup.py sdist bdist_wheel --plat-name win_amd64
          python -m twine upload -u __token__ -p ${{secrets.PYPI_API_TOKEN}} dist/* --skip-existing
          rm -r build
          rm -r install

      - name: build Windows-32bit
        if: matrix.os == 'windows-latest'
        run: |
          mkdir build
          mkdir install
          cd build
          cmake -G "Visual Studio 16" -A Win32 -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF -DCMAKE_INSTALL_PREFIX=../install ..
          cmake --build .
          cd ../
          python.exe setup.py sdist bdist_wheel --plat-name win32
          python -m twine upload -u __token__ -p ${{secrets.PYPI_API_TOKEN}} dist/* --skip-existing
          rm -r build
          rm -r install

      - name: build ubuntu 
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir build
          cd build
          cmake  -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF ..
          make
          cd ..

      - name: build ubuntu manylinux
        if: matrix.os == 'ubuntu-latest'
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'

      - name: upload manylinux
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m twine upload -u __token__ -p ${{secrets.PYPI_API_TOKEN}} dist/*-manylinux*.whl --skip-existing

      - name: build macos
        if: matrix.os == 'macos-latest'
        run: |
          mkdir build
          cd build
          cmake  -DBUILD_PYTHON:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON  -Dndicapi_BUILD_APPLICATIONS:BOOL=OFF ..
          make
          cd ..
          python setup.py sdist bdist_wheel
          python -m twine upload -u __token__ -p ${{secrets.PYPI_API_TOKEN}} dist/* --skip-existing

